#define BATT_LEVEL_PIN    A17
#define HEARTBEAT_LED     36
#define CURRENT_SENSOR    A16
#define AUX_LED           A14
#define CENTRAL_LED       30
#define LED               13
#define WIND_SENSOR       A9
#define BUTTON_PIN        26
#define SERVO1_PIN        4
#define SERVO2_PIN        5
#define SERVO3_PIN        6
#define SERVO4_PIN        9
